<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>LilyPond markup</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>([-_^](\s*))?(((\\markup\s*)({))|((\\markuplist\s*)({)))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.keyword.lilypond</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.keyword.lilypond</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.other.lilypond</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.keyword.lilypond</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>entity.other.lilypond</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.lilypond</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.lilypond.markupmode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.lilypond-internals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lilypond-notemode-explicit</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lilypond-schememode</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>({)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.lilypond</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.lilypond</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.lilypond.markupmode.nested</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.lilypond-notemode-explicit</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lilypond-internals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lilypond-notemode-explicit</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lilypond-schememode</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.lilypond-markupmode</string>
	<key>uuid</key>
	<string>8e4f5e35-589f-4645-b6b0-67ec5971210a</string>
</dict>
</plist>
