<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>LilyPond note mode</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>content</key>
			<string>LilyPond chord</string>
			<key>match</key>
			<string>&lt;(?!&lt;)|(?&lt;!\\)&gt;(?!&gt;)(\s*(128|64|32|16|8|4|2|1|\\breve|\\longa|\\maxima)(\s*[.]\s*)*((\s*\*\s*\d+(\/\d+)?)+)?)?</string>
			<key>name</key>
			<string>keyword.operator.chord.lilypond</string>
		</dict>
		<dict>
			<key>content</key>
			<string>LilyPond manual beam</string>
			<key>match</key>
			<string>([_^-]\s*)?\[|\]</string>
			<key>name</key>
			<string>constant.numeric.beam.lilypond</string>
		</dict>
		<dict>
			<key>content</key>
			<string>LilyPond polyphony delimiter</string>
			<key>match</key>
			<string>&lt;&lt;|&gt;&gt;</string>
			<key>name</key>
			<string>constant.language.polydelim.lilypond</string>
		</dict>
		<dict>
			<key>content</key>
			<string>LilyPond polyphony separator</string>
			<key>match</key>
			<string>\\\\</string>
			<key>name</key>
			<string>constant.character.polysep.lilypond</string>
		</dict>
		<dict>
			<key>content</key>
			<string>LilyPond articulation mark</string>
			<key>match</key>
			<string>[-_^][-_^+|&gt;.]</string>
			<key>name</key>
			<string>string.interpolated.articulation.lilypond</string>
		</dict>
		<dict>
			<key>content</key>
			<string>LilyPond tie or slur</string>
			<key>match</key>
			<string>([_^-]\s*)?\(|[_^-]?~|\)</string>
			<key>name</key>
			<string>support.function.tieslur.lilypond</string>
		</dict>
		<dict>
			<key>content</key>
			<string>LilyPond phrasing slur</string>
			<key>match</key>
			<string>([_^-]\s*)?\\\(|\\\)</string>
			<key>name</key>
			<string>support.constant.phraslur.lilypond</string>
		</dict>
		<dict>
			<key>content</key>
			<string>LilyPond ligature</string>
			<key>match</key>
			<string>([_^-]\s*)?\\\[|\\\]</string>
			<key>name</key>
			<string>support.constant.ligature.lilypond</string>
		</dict>
		<dict>
			<key>content</key>
			<string>LilyPond bar line</string>
			<key>match</key>
			<string>[|]</string>
			<key>name</key>
			<string>support.type.barline.lilypond</string>
		</dict>
		<dict>
			<key>content</key>
			<string>LilyPond hairpin</string>
			<key>match</key>
			<string>\\[&lt;!&gt;]</string>
			<key>name</key>
			<string>support.variable.hairpin.lilypond</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>({)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.lilypond</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.lilypond</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.lilypond.notemode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.lilypond-notenames</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lilypond-internals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lilypond-markupmode</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lilypond-figbassmode</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lilypond-schememode</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.lilypond-notenames</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.lilypond-internals</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.lilypond-figbassmode</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.lilypond-schememode</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.lilypond-notemode</string>
	<key>uuid</key>
	<string>6f1e8a88-4aa8-4980-9a16-472406a2055c</string>
</dict>
</plist>
