<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>LilyPond note mode</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.lilypond-notedrum</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>({)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.lilypond</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.lilypond</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.lilypond.notemode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>source.lilypond-notenames</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.lilypond-internals</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.lilypond-drummode</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.lilypond-lyricsmode</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.lilypond-notemode-explicit</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.lilypond-markupmode</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.lilypond-figbassmode</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.lilypond-schememode</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.lilypond-notemode</string>
	<key>uuid</key>
	<string>6f1e8a88-4aa8-4980-9a16-472406a2055c</string>
</dict>
</plist>
