<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ly</string>
	</array>
	<key>name</key>
	<string>LilyPond</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.lilypond-notenames</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.lilypond-internals</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.lilypond-notemode</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.lilypond-figbassmode</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.lilypond-schememode</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.lilypond</string>
	<key>uuid</key>
	<string>f9b5511b-f318-412c-9078-fb703c82528e</string>
</dict>
</plist>
