<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>LilyPond lyrics scopes</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>([-_^](\s*))?(((\\lyrics\s*)({))|((\\lyricmode\s*)({))|((\\addlyrics\s*)({))|((\\lyricsto\s*(".*")\s*)({))|(((\\lyricsto)\s*(\S*)\s*)({)))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.keyword.lilypond</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.keyword.lilypond</string>
				</dict>
				<key>12</key>
				<dict>
					<key>name</key>
					<string>entity.other.lilypond</string>
				</dict>
				<key>14</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.keyword.lilypond</string>
				</dict>
				<key>15</key>
				<dict>
					<key>name</key>
					<string>string.lilypond</string>
				</dict>
				<key>16</key>
				<dict>
					<key>name</key>
					<string>entity.other.lilypond</string>
				</dict>
				<key>19</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.keyword.lilypond</string>
				</dict>
				<key>21</key>
				<dict>
					<key>name</key>
					<string>entity.other.lilypond</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.keyword.lilypond</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.other.lilypond</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.keyword.lilypond</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>entity.other.lilypond</string>
				</dict>
			</dict>
			<key>end</key>
			<string>}</string>
			<key>endCaptures</key>
			<dict>
			</dict>
			<key>name</key>
			<string>meta.lilypond.lyricsmode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#separator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#melisma</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#elision</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lilypond-internals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lilypond-markupmode</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lilypond-schememode</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>({)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.lilypond</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.lilypond</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.lilypond.lyricsmode.nested</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#separator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#melisma</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#elision</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lilypond-internals</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lilypond-markupmode</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lilypond-schememode</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>elision</key>
		<dict>
			<key>content</key>
			<string>Lyrics elision</string>
			<key>match</key>
			<string>(?&lt;=\S)[~_](?=\S)</string>
			<key>name</key>
			<string>constant.language.elision.lilypond</string>
		</dict>
		<key>melisma</key>
		<dict>
			<key>content</key>
			<string>Lyrics melisma</string>
			<key>match</key>
			<string>(?&lt;=\s)(_)(?=\s)</string>
			<key>name</key>
			<string>storage.type.number.manualmelisma.lilypond</string>
		</dict>
		<key>separator</key>
		<dict>
			<key>content</key>
			<string>Lyrics syllable separator</string>
			<key>match</key>
			<string>\s*--\s*</string>
			<key>name</key>
			<string>support.function.syllableseparator.lilypond</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.lilypond-lyricsmode</string>
	<key>uuid</key>
	<string>f2f1b98b-daa1-4dfa-9645-d18d4b4307c9</string>
</dict>
</plist>
