<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ly</string>
	</array>
	<key>name</key>
	<string>LilyPond</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.lilypond-internals</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>([-_^](\s*))?((\\figures\s*)({))|((\\figuremode\s*)({))</string>
			<key>beginCaptures</key>
			<dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.keyword.lilypond</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.other.lilypond</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.keyword.lilypond</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>entity.other.lilypond</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.lilypond</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.lilypond.figbassmode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#figbass</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>({)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.lilypond</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.lilypond</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.lilypond.lilypondmainmode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lilypond-notemode</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\$(`|')?\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.lilypond.schememode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#scheme</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lisp</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>#(`|')?\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.lilypond.schememode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#scheme</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lisp</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>\s</string>
			<key>name</key>
			<string>meta.lilypond.schememode</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#scheme</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lisp</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>figbass</key>
		<dict>
			<key>name</key>
			<string>meta.lilypond.figbass</string>
			<key>patterns</key>
			<array>
			</array>
		</dict>
		<key>scheme</key>
		<dict>
			<key>begin</key>
			<string>\(</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.scheme.scheme.lilypond</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#scheme</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.lisp</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.lilypond</string>
	<key>uuid</key>
	<string>f9b5511b-f318-412c-9078-fb703c82528e</string>
</dict>
</plist>
